"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{requireProfile}from"@/lib/auth";import{createClient}from"@/lib/supabase/server";import{interviewIdSchema,interviewerAssignmentSchema,interviewSchema,notificationIdSchema}from"@/lib/validation";import type{ActionState}from"@/app/(protected)/actions";
const errorMessage=(error:unknown)=>error instanceof Error?error.message:"The operation could not be completed.";
const payload=(fd:FormData)=>({candidate_id:String(fd.get("candidate_id")??""),stage_id:String(fd.get("stage_id")??""),scheduled_at:String(fd.get("scheduled_at")??""),timezone:String(fd.get("timezone")??""),method:String(fd.get("method")??""),location:String(fd.get("location")??""),meeting_link:String(fd.get("meeting_link")??""),notes:String(fd.get("notes")??"")});
export async function createInterview(_:ActionState,fd:FormData):Promise<ActionState>{await requireProfile(["HR_RECRUITER"]);const parsed=interviewSchema.safeParse(payload(fd));if(!parsed.success)return{error:parsed.error.issues[0].message};const s=await createClient();const{data,error}=await s.rpc("schedule_interview",{p_candidate_id:parsed.data.candidate_id,p_stage_id:parsed.data.stage_id,p_scheduled_at:parsed.data.scheduled_at,p_timezone:parsed.data.timezone,p_method:parsed.data.method,p_location:parsed.data.location,p_meeting_link:parsed.data.meeting_link,p_notes:parsed.data.notes});if(error)return{error:error.message};redirect(`/interviews/${data}`)}
export async function editInterview(_:ActionState,fd:FormData):Promise<ActionState>{await requireProfile(["HR_RECRUITER"]);const id=interviewIdSchema.safeParse(fd.get("interview_id"));if(!id.success)return{error:id.error.issues[0].message};const parsed=interviewSchema.safeParse(payload(fd));if(!parsed.success)return{error:parsed.error.issues[0].message};const s=await createClient();const{error}=await s.rpc("update_interview",{p_interview_id:id.data,p_stage_id:parsed.data.stage_id,p_scheduled_at:parsed.data.scheduled_at,p_timezone:parsed.data.timezone,p_method:parsed.data.method,p_location:parsed.data.location,p_meeting_link:parsed.data.meeting_link,p_notes:parsed.data.notes});if(error)return{error:error.message};redirect(`/interviews/${id.data}`)}
export async function cancelInterview(fd:FormData){await requireProfile(["HR_RECRUITER"]);const id=interviewIdSchema.parse(fd.get("interview_id"));const s=await createClient();const{error}=await s.rpc("cancel_interview",{p_interview_id:id});if(error)throw new Error(error.message);revalidatePath(`/interviews/${id}`);}
export async function assignInterviewers(_:ActionState,fd:FormData):Promise<ActionState>{await requireProfile(["HR_RECRUITER"]);const parsed=interviewerAssignmentSchema.safeParse({interview_id:String(fd.get("interview_id")??""),interviewer_ids:fd.getAll("interviewer_ids").map(String)});if(!parsed.success)return{error:parsed.error.issues[0].message};const s=await createClient();const{error}=await s.rpc("assign_interviewers",{p_interview_id:parsed.data.interview_id,p_interviewer_profile_ids:parsed.data.interviewer_ids,p_feedback_required:true});if(error)return{error:error.message};revalidatePath(`/interviews/${parsed.data.interview_id}`);return{success:"Interviewers assigned and notified."}}
export async function markNotificationRead(fd:FormData){const profile=await requireProfile();const id=notificationIdSchema.parse(fd.get("notification_id"));const s=await createClient();const{error}=await s.from("notifications").update({read_at:new Date().toISOString()}).eq("id",id).eq("recipient_profile_id",profile.id);if(error)throw new Error(errorMessage(error));revalidatePath("/notifications");revalidatePath("/dashboard");}
