import{describe,expect,it,vi}from"vitest";import{readFileSync}from"node:fs";import{minimumEvidence,summarizeSubmittedFeedback,validateSummary}from"@/lib/ai-feedback";import type{SubmittedEvaluation}from"@/lib/decision-support";
const root=process.cwd(),read=(path:string)=>readFileSync(`${root}/${path}`,"utf8");
const evaluation:SubmittedEvaluation={id:"feedback-secret-id",candidate_id:"candidate-secret-id",stage_id:"stage-secret-id",interview_id:"interview-secret-id",remarks:"Explained the implementation clearly.",strengths:"Strong TypeScript evidence.",concerns:"Needs more detail on monitoring.",submitted_at:"2026-09-13T10:00:00Z",author:{full_name:"Private Interviewer"},feedback_ratings:[{criterion_id:"criterion-secret-id",criterion_name:"Technical communication",criterion_weight:100,rating:4}]};
describe("responsible AI feedback summary",()=>{
  it("minimises submitted evidence before provider use",()=>expect(minimumEvidence([evaluation])).toEqual([{remarks:evaluation.remarks,strengths:evaluation.strengths,concerns:evaluation.concerns,ratings:[{criterion:"Technical communication",rating:4}]}]));
  it("returns validated structured provider output",async()=>{const provider={generate:vi.fn().mockResolvedValue({strengths:["Strong TypeScript evidence."],points_for_review:["Monitoring detail needs review."],themes:["Clear technical communication."]})};const state=await summarizeSubmittedFeedback([evaluation],provider);expect(state.status).toBe("READY");expect(provider.generate).toHaveBeenCalledWith(minimumEvidence([evaluation]))});
  it("fails closed on invalid or extra output fields",async()=>{const state=await summarizeSubmittedFeedback([evaluation],{generate:async()=>({strengths:[],points_for_review:[],themes:[],decision:"HIRE"})});expect(state.status).toBe("UNAVAILABLE")});
  it.each(["Recommend hire.","Rank this candidate first.","Predict success.","Their ethnicity may help."])("rejects prohibited output: %s",text=>expect(validateSummary({strengths:[text],points_for_review:[],themes:[]})).toBeNull());
  it("keeps provider failures non-blocking",async()=>{const state=await summarizeSubmittedFeedback([evaluation],{generate:async()=>{throw new Error("provider failure")}});expect(state).toEqual({status:"UNAVAILABLE",message:"AI summary is temporarily unavailable. Review the submitted feedback below."})});
  it("keeps provider timeouts non-blocking",async()=>{const state=await summarizeSubmittedFeedback([evaluation],{generate:async()=>{throw new DOMException("Timed out","TimeoutError")}});expect(state).toEqual({status:"UNAVAILABLE",message:"AI summary is temporarily unavailable. Review the submitted feedback below."})});
  it("does not call a provider without submitted evidence",async()=>{const provider={generate:vi.fn()};const state=await summarizeSubmittedFeedback([],provider);expect(state.status).toBe("EMPTY");expect(provider.generate).not.toHaveBeenCalled()});
  it("does not fabricate a summary without provider configuration",async()=>expect((await summarizeSubmittedFeedback([evaluation])).status).toBe("UNAVAILABLE"));
});
describe("responsible AI server contracts",()=>{
  const action=read("app/(protected)/candidates/[id]/decision-room/actions.ts"),adapter=read("lib/gemini-feedback-provider.ts"),factory=read("lib/feedback-provider.ts"),component=read("components/ai-feedback-summary.tsx");
  it("authorizes HR and Management but not Interviewer",()=>{expect(action).toContain('requireProfile(["HR_RECRUITER","MANAGEMENT"])');expect(action).not.toContain('"INTERVIEWER"]')});
  it("queries only submitted interviewer evidence for the current candidate stage",()=>{for(const clause of['.eq("candidate_id",candidate.id)','.eq("stage_id",candidate.current_stage_id)','.eq("status","SUBMITTED")','.eq("author_role","INTERVIEWER")','.not("interview_id","is",null)'])expect(action).toContain(clause)});
  it("selects Gemini while preserving the OpenAI adapter",()=>{expect(factory).toContain('case"gemini":return configuredGeminiProvider()');expect(factory).toContain('case"openai":return configuredOpenAiProvider()')});
  it("uses a server-only Gemini provider and private environment names",()=>{expect(adapter).toContain('import"server-only"');expect(adapter).toContain("GEMINI_API_KEY");expect(adapter).toContain("GEMINI_MODEL");expect(adapter).not.toContain("NEXT_PUBLIC_")});
  it("uses the configured model with structured non-retained output and a bounded timeout",()=>{expect(adapter).toContain("model:this.model");expect(adapter).toContain("store:false");expect(adapter).toContain("timeout_ms:10_000");expect(adapter).toContain('mime_type:"application/json"');expect(adapter).toContain("additionalProperties:false")});
  it("keeps recommendation, ranking, prediction and inference constraints",()=>{for(const text of["Do not recommend hire or reject","rank or compare candidates","predict success","infer protected characteristics","generate new evidence"])expect(adapter).toContain(text)});
  it("does not mutate recruitment state or persist AI output",()=>{expect(action).not.toMatch(/\.update\(|\.insert\(|\.upsert\(|\.delete\(|move_candidate|set_candidate_outcome/i);expect(adapter).not.toMatch(/\.from\(|\.insert\(|\.update\(/)});
  it("keeps human evidence authoritative and labels generated content",()=>{expect(component).toContain("AI-generated summary of submitted feedback.");expect(component).toContain("Final hiring decisions remain with authorised staff.");expect(component).toContain('href="#source-feedback"')});
});
