// @vitest-environment node
import{afterAll,beforeAll,describe,expect,it}from"vitest";import{createClient,type SupabaseClient}from"@supabase/supabase-js";import{deriveStageStays,stageDurationDays}from"@/lib/reporting";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,service=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});let hr:SupabaseClient,management:SupabaseClient,interviewer:SupabaseClient,hrId="",vacancyId="",candidateId="",firstStage="",secondStage="",auditId="";const exportIds:string[]=[];
async function login(email:string,password:string){const value=createClient(url,anon,{auth:{persistSession:false}});const{error}=await value.auth.signInWithPassword({email,password});if(error)throw error;return value}async function profile(value:SupabaseClient){const{data:{user}}=await value.auth.getUser();const{data,error}=await service.from("user_profiles").select("id").eq("authentication_user_id",user!.id).single();if(error)throw error;return data.id as string}
describe.sequential("connected Phase F reporting and oversight security",()=>{
  beforeAll(async()=>{[hr,management,interviewer]=await Promise.all([login(process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!),login("management@hirelens.demo",process.env.SEED_MANAGEMENT_PASSWORD!),login("interviewer@hirelens.demo",process.env.SEED_INTERVIEWER_PASSWORD!)]);hrId=await profile(hr);const suffix=crypto.randomUUID();const{data:vacancy,error:ve}=await service.from("vacancies").insert({title:`Phase F Reporting ${suffix}`,department:"Reporting QA",location:"Colombo",employment_type:"FULL_TIME",description:"Disposable Phase F connected fixture.",created_by:hrId}).select("id").single();if(ve)throw ve;vacancyId=vacancy.id;const{data:stages,error:se}=await service.from("vacancy_stages").insert([{vacancy_id:vacancyId,name:"Applied",stage_order:0},{vacancy_id:vacancyId,name:"Review",stage_order:1}]).select("id,stage_order").order("stage_order");if(se)throw se;firstStage=stages[0].id;secondStage=stages[1].id;const{data:candidate,error:ce}=await service.from("candidates").insert({vacancy_id:vacancyId,current_stage_id:secondStage,full_name:'Maya, "Phase F"',email:`phase-f-${suffix}@example.com`,phone:"+94 77 555 1111",source:"QA",notes:"Disposable",status:"ACTIVE",created_by:hrId,created_at:"2026-09-01T00:00:00Z"}).select("id").single();if(ce)throw ce;candidateId=candidate.id;const{error:he}=await service.from("candidate_stage_history").insert({candidate_id:candidateId,previous_stage_id:firstStage,new_stage_id:secondStage,changed_by:hrId,changed_at:"2026-09-03T12:00:00Z"});if(he)throw he;const{data:event,error:ae}=await service.from("audit_events").insert({actor_profile_id:hrId,action:"PHASE_F_FILTER_TEST",target_type:"CANDIDATE",target_id:candidateId,candidate_id:candidateId,vacancy_id:vacancyId,metadata:{safe_context:"connected verification"}}).select("id").single();if(ae)throw ae;auditId=event.id},60_000);
  afterAll(async()=>{if(vacancyId)await service.from("audit_events").delete().eq("vacancy_id",vacancyId);if(exportIds.length)await service.from("audit_events").delete().in("id",exportIds);if(candidateId){await service.from("candidate_stage_history").delete().eq("candidate_id",candidateId);for(const table of["activity_logs","feedback_submissions","progression_overrides"])await service.from(table).delete().eq("candidate_id",candidateId);await service.from("candidates").delete().eq("id",candidateId)}if(vacancyId){await service.from("vacancy_stages").delete().eq("vacancy_id",vacancyId);await service.from("vacancies").delete().eq("id",vacancyId)}await Promise.all([hr?.auth.signOut(),management?.auth.signOut(),interviewer?.auth.signOut()])},60_000);
  it("lets HR read actor, action, target, and timestamp safely",async()=>{const{data,error}=await hr.rpc("recruitment_audit_feed",{p_actor_profile_id:hrId,p_action:"PHASE_F_FILTER_TEST",p_candidate_id:candidateId,p_vacancy_id:vacancyId,p_oldest_first:false});expect(error).toBeNull();expect(data).toHaveLength(1);expect(data?.[0]).toMatchObject({id:auditId,actor_name:"Harper Reed",action:"PHASE_F_FILTER_TEST",candidate_name:'Maya, "Phase F"'});expect(data?.[0].created_at).toBeTruthy()});
  it("lets Management read the same safe audit view",async()=>{const{data,error}=await management.rpc("recruitment_audit_feed",{p_actor_profile_id:null,p_action:"PHASE_F_FILTER_TEST",p_candidate_id:null,p_vacancy_id:vacancyId,p_oldest_first:false});expect(error).toBeNull();expect(data?.[0].vacancy_title).toContain("Phase F Reporting")});
  it("denies broad audit access to Interviewer",async()=>{const{error}=await interviewer.rpc("recruitment_audit_feed",{p_actor_profile_id:null,p_action:null,p_candidate_id:null,p_vacancy_id:null,p_oldest_first:false});expect(error).not.toBeNull()});
  it("keeps audit records immutable for HR and Management",async()=>{for(const value of[hr,management]){expect((await value.from("audit_events").update({action:"TAMPERED"}).eq("id",auditId)).error).not.toBeNull();expect((await value.from("audit_events").delete().eq("id",auditId)).error).not.toBeNull()}});
  it("records HR report export as an audit event",async()=>{const{data,error}=await hr.rpc("record_recruitment_report_export");expect(error).toBeNull();expect(data).toBeTruthy();exportIds.push(data);const{data:event}=await service.from("audit_events").select("actor_profile_id,action,target_type,metadata").eq("id",data).single();expect(event).toMatchObject({actor_profile_id:hrId,action:"RECRUITMENT_REPORT_EXPORTED",target_type:"REPORT",metadata:{format:"CSV"}})});
  it("records Management report export with its own actor",async()=>{const managementId=await profile(management);const{data,error}=await management.rpc("record_recruitment_report_export");expect(error).toBeNull();exportIds.push(data);expect((await service.from("audit_events").select("actor_profile_id").eq("id",data).single()).data?.actor_profile_id).toBe(managementId)});
  it("denies report export to Interviewer",async()=>expect((await interviewer.rpc("record_recruitment_report_export")).error).not.toBeNull());
  it("keeps Management recruitment records read-only",async()=>{const candidateUpdate=await management.from("candidates").update({full_name:"Changed"}).eq("id",candidateId).select("id"),vacancyUpdate=await management.from("vacancies").update({title:"Changed"}).eq("id",vacancyId).select("id");expect(candidateUpdate.error).toBeNull();expect(candidateUpdate.data).toEqual([]);expect(vacancyUpdate.error).toBeNull();expect(vacancyUpdate.data).toEqual([]);expect((await service.from("candidates").select("full_name").eq("id",candidateId).single()).data?.full_name).toBe('Maya, "Phase F"');expect((await service.from("vacancies").select("title").eq("id",vacancyId).single()).data?.title).toContain("Phase F Reporting")});
  it("supports role-safe candidate filters through existing RLS",async()=>{for(const value of[hr,management]){const{data,error}=await value.from("candidates").select("id").eq("vacancy_id",vacancyId).eq("current_stage_id",secondStage).eq("status","ACTIVE").ilike("full_name","%Phase F%");expect(error).toBeNull();expect(data).toEqual([{id:candidateId}])}});
  it("preserves exact stored stage history for duration analytics",async()=>{const{data,error}=await management.from("candidate_stage_history").select("candidate_id,previous_stage_id,new_stage_id,changed_at").eq("candidate_id",candidateId);expect(error).toBeNull();const stays=deriveStageStays({id:candidateId,current_stage_id:secondStage,created_at:"2026-09-01T00:00:00Z",status:"ACTIVE"},data!,new Map([[firstStage,"Applied"],[secondStage,"Review"]]));expect(stageDurationDays(stays[0].enteredAt,stays[0].leftAt)).toBe(2.5);expect(stays[1].leftAt).toBeNull()});
  it("returns no fabricated audit matches for an unrelated action",async()=>{const{data,error}=await management.rpc("recruitment_audit_feed",{p_actor_profile_id:null,p_action:"DOES_NOT_EXIST",p_candidate_id:null,p_vacancy_id:vacancyId,p_oldest_first:false});expect(error).toBeNull();expect(data).toEqual([])});
});
