// @vitest-environment node
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL!;
const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const service=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
let hr:SupabaseClient, interviewerA:SupabaseClient, interviewerB:SupabaseClient, interviewerC:SupabaseClient, management:SupabaseClient;
let hrId="",aId="",bId="",cId="",vacancyId="";
const userIds:string[]=[];const profileIds:string[]=[];const stageIds:string[]=[];const candidateIds:string[]=[];const interviewIds:string[]=[];const feedbackIds:string[]=[];

async function login(email:string,password:string){const client=createClient(url,anon,{auth:{persistSession:false}});const{error}=await client.auth.signInWithPassword({email,password});if(error)throw error;return client}
async function profileId(client:SupabaseClient){const{data:{user}}=await client.auth.getUser();const{data,error}=await service.from("user_profiles").select("id").eq("authentication_user_id",user!.id).single();if(error)throw error;return data.id as string}
async function createInterviewer(label:string){const password=`PhaseD#${crypto.randomUUID()}aA1`;const email=`phase-d-${label.toLowerCase().replaceAll(" ","-")}-${crypto.randomUUID()}@hirelens.test`;const{data:user,error}=await service.auth.admin.createUser({email,password,email_confirm:true});if(error)throw error;userIds.push(user.user.id);const{data:profile,error:profileError}=await service.from("user_profiles").insert({authentication_user_id:user.user.id,full_name:`Phase D ${label}`,role:"INTERVIEWER"}).select("id").single();if(profileError)throw profileError;profileIds.push(profile.id);return{client:await login(email,password),id:profile.id as string}}
const ratings=(criterionIds:string[],value:number)=>criterionIds.map(criterion_id=>({criterion_id,rating:value}));

describe.sequential("connected Phase D governance",()=>{
  let criteriaIds:string[]=[];let noEvidence="",gated="",cancelled="",overrideCandidate="",closed="";let gatedInterview="",unrelatedInterview="";
  beforeAll(async()=>{
    [hr,interviewerA,management]=await Promise.all([login(process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!),login("interviewer@hirelens.demo",process.env.SEED_INTERVIEWER_PASSWORD!),login("management@hirelens.demo",process.env.SEED_MANAGEMENT_PASSWORD!)]);
    const probe=await interviewerA.rpc("has_submitted_own_interview_feedback",{p_interview_id:crypto.randomUUID()});
    if(probe.error?.code==="PGRST202"||probe.error?.message.includes("has_submitted_own_interview_feedback"))throw new Error("Apply supabase/migrations/202609120003_governance.sql before running connected Phase D tests.");
    hrId=await profileId(hr);aId=await profileId(interviewerA);
    const [b,c]=await Promise.all([createInterviewer("Interviewer B"),createInterviewer("Interviewer C")]);interviewerB=b.client;bId=b.id;interviewerC=c.client;cId=c.id;
    const suffix=crypto.randomUUID();const{data:vacancy,error:vacancyError}=await service.from("vacancies").insert({title:`Phase D Governance ${suffix}`,department:"Quality",location:"Colombo",employment_type:"FULL_TIME",description:"Disposable Phase D governance verification fixture.",created_by:hrId}).select("id").single();if(vacancyError)throw vacancyError;vacancyId=vacancy.id;
    const{data:stages,error:stageError}=await service.from("vacancy_stages").insert(["Technical Interview","Final Interview","Offer"].map((name,stage_order)=>({vacancy_id:vacancyId,name,stage_order}))).select("id,stage_order").order("stage_order");if(stageError)throw stageError;stageIds.push(...stages.map(row=>row.id));
    const criteria=[{id:null,name:"Technical",description:"Technical evidence",weight:60,rating_required:true,display_order:0},{id:null,name:"Communication",description:"Communication evidence",weight:40,rating_required:true,display_order:1}];const configured=await hr.rpc("save_evaluation_criteria",{p_vacancy_id:vacancyId,p_stage_id:stageIds[0],p_criteria:criteria});if(configured.error)throw configured.error;const{data:criterionRows}=await service.from("evaluation_criteria").select("id").eq("vacancy_id",vacancyId).eq("stage_id",stageIds[0]).order("display_order");criteriaIds=(criterionRows??[]).map(row=>row.id);
    const candidates=[{label:"no-evidence",status:"ACTIVE"},{label:"gated",status:"ACTIVE"},{label:"cancelled",status:"ACTIVE"},{label:"override",status:"ACTIVE"},{label:"closed",status:"CLOSED"}];const{data:candidateRows,error:candidateError}=await service.from("candidates").insert(candidates.map(item=>({vacancy_id:vacancyId,current_stage_id:stageIds[0],full_name:`Phase D ${item.label}`,email:`${item.label}-${suffix}@example.com`,phone:"+94 77 700 8000",source:"QA",notes:"Disposable",status:item.status,created_by:hrId}))).select("id,email");if(candidateError)throw candidateError;candidateIds.push(...candidateRows.map(row=>row.id));const byLabel=(label:string)=>candidateRows.find(row=>row.email.startsWith(`${label}-`))!.id;noEvidence=byLabel("no-evidence");gated=byLabel("gated");cancelled=byLabel("cancelled");overrideCandidate=byLabel("override");closed=byLabel("closed");
    const scheduled=new Date(Date.now()+172_800_000).toISOString();const definitions=[{candidate_id:gated,status:"SCHEDULED",method:"VIDEO"},{candidate_id:gated,status:"SCHEDULED",method:"PHONE"},{candidate_id:cancelled,status:"CANCELLED",method:"PHONE"},{candidate_id:overrideCandidate,status:"SCHEDULED",method:"PHONE"}];const{data:interviews,error:interviewError}=await service.from("interviews").insert(definitions.map(item=>({...item,vacancy_id:vacancyId,stage_id:stageIds[0],scheduled_at:scheduled,timezone:"Asia/Colombo",meeting_link:item.method==="VIDEO"?"https://meet.example.com/phase-d":null,cancelled_at:item.status==="CANCELLED"?new Date().toISOString():null,created_by:hrId}))).select("id,candidate_id,status,method");if(interviewError)throw interviewError;interviewIds.push(...interviews.map(row=>row.id));gatedInterview=interviews.find(row=>row.candidate_id===gated&&row.method==="VIDEO")!.id;unrelatedInterview=interviews.find(row=>row.candidate_id===gated&&row.method==="PHONE")!.id;const cancelledInterview=interviews.find(row=>row.candidate_id===cancelled)!.id;const overrideInterview=interviews.find(row=>row.candidate_id===overrideCandidate)!.id;
    const{error:assignmentError}=await service.from("interview_assignments").insert([{interview_id:gatedInterview,interviewer_profile_id:aId,assigned_by:hrId,feedback_required:true},{interview_id:gatedInterview,interviewer_profile_id:bId,assigned_by:hrId,feedback_required:true},{interview_id:unrelatedInterview,interviewer_profile_id:cId,assigned_by:hrId,feedback_required:false},{interview_id:cancelledInterview,interviewer_profile_id:bId,assigned_by:hrId,feedback_required:true},{interview_id:overrideInterview,interviewer_profile_id:bId,assigned_by:hrId,feedback_required:true}]);if(assignmentError)throw assignmentError;
  },60_000);

  afterAll(async()=>{if(candidateIds.length){const{data:feedback}=await service.from("feedback_submissions").select("id").in("candidate_id",candidateIds);const ids=(feedback??[]).map(row=>row.id);if(ids.length)await service.from("feedback_ratings").delete().in("feedback_submission_id",ids);await service.from("feedback_submissions").delete().in("candidate_id",candidateIds);for(const table of ["notifications","progression_overrides","audit_events","activity_logs","candidate_stage_history"])await service.from(table).delete().in("candidate_id",candidateIds)}if(interviewIds.length){await service.from("interview_assignments").delete().in("interview_id",interviewIds);await service.from("interviews").delete().in("id",interviewIds)}if(vacancyId){await service.from("evaluation_criteria").delete().eq("vacancy_id",vacancyId);await service.from("audit_events").delete().eq("vacancy_id",vacancyId)}if(candidateIds.length)await service.from("candidates").delete().in("id",candidateIds);if(stageIds.length)await service.from("vacancy_stages").delete().in("id",stageIds);if(vacancyId)await service.from("vacancies").delete().eq("id",vacancyId);if(profileIds.length)await service.from("user_profiles").delete().in("id",profileIds);for(const id of userIds)await service.auth.admin.deleteUser(id);await Promise.all([hr?.auth.signOut(),interviewerA?.auth.signOut(),interviewerB?.auth.signOut(),interviewerC?.auth.signOut(),management?.auth.signOut()])},60_000);

  it("allows normal sequential progression when no evidence is required",async()=>{expect((await hr.rpc("move_candidate",{p_candidate_id:noEvidence,p_target_stage_id:stageIds[1]})).error).toBeNull()});
  it("blocks pending evidence through the RPC and direct workflow-field updates",async()=>{expect((await hr.rpc("move_candidate",{p_candidate_id:gated,p_target_stage_id:stageIds[1]})).error?.message).toContain("2 required feedback");const direct=await hr.from("candidates").update({current_stage_id:stageIds[1]}).eq("id",gated);expect(direct.error).toBeTruthy()});
  it("rejects blank, whitespace, non-HR, and unnecessary overrides",async()=>{for(const reason of ["","   "])expect((await hr.rpc("move_candidate",{p_candidate_id:overrideCandidate,p_target_stage_id:stageIds[1],p_override:true,p_override_reason:reason})).error?.message).toContain("Override reason is required");expect((await interviewerA.rpc("move_candidate",{p_candidate_id:overrideCandidate,p_target_stage_id:stageIds[1],p_override:true,p_override_reason:"Not authorised"})).error).toBeTruthy();expect((await management.rpc("move_candidate",{p_candidate_id:overrideCandidate,p_target_stage_id:stageIds[1],p_override:true,p_override_reason:"Not authorised"})).error).toBeTruthy();expect((await hr.rpc("move_candidate",{p_candidate_id:noEvidence,p_target_stage_id:stageIds[2],p_override:true,p_override_reason:"Not required"})).error?.message).toContain("Override is not required")});
  it("keeps peer drafts and submissions hidden before own submission",async()=>{const draft=await interviewerB.rpc("save_feedback_draft",{p_interview_id:gatedInterview,p_remarks:"Private B draft",p_strengths:"",p_concerns:"",p_ratings:ratings(criteriaIds,3)});expect(draft.error).toBeNull();feedbackIds.push(draft.data);expect((await interviewerA.from("feedback_submissions").select("id").eq("id",draft.data)).data).toEqual([]);expect((await interviewerB.rpc("submit_interview_feedback",{p_interview_id:gatedInterview,p_remarks:"Submitted B evidence",p_strengths:"Good",p_concerns:"",p_ratings:ratings(criteriaIds,3)})).error).toBeNull();expect((await interviewerA.from("feedback_submissions").select("id").eq("id",draft.data)).data).toEqual([])});
  it("partial completion remains blocked",async()=>{expect((await hr.rpc("feedback_completion",{p_candidate_id:gated,p_stage_id:stageIds[0]})).data?.[0]).toMatchObject({required_count:2,submitted_count:1,complete:false});expect((await hr.rpc("move_candidate",{p_candidate_id:gated,p_target_stage_id:stageIds[1]})).error).toBeTruthy()});
  it("releases submitted peers only for the same interview after own submission",async()=>{const unrelated=await interviewerC.rpc("submit_interview_feedback",{p_interview_id:unrelatedInterview,p_remarks:"Unrelated interview evidence",p_strengths:"",p_concerns:"",p_ratings:ratings(criteriaIds,4)});expect(unrelated.error).toBeNull();feedbackIds.push(unrelated.data);const own=await interviewerA.rpc("submit_interview_feedback",{p_interview_id:gatedInterview,p_remarks:"Submitted A evidence",p_strengths:"Strong",p_concerns:"",p_ratings:ratings(criteriaIds,5)});expect(own.error).toBeNull();feedbackIds.push(own.data);const{data:visible}=await interviewerA.from("feedback_submissions").select("id,interview_id,status").eq("candidate_id",gated);expect(visible?.some(row=>row.id===feedbackIds[0]&&row.interview_id===gatedInterview)).toBe(true);expect(visible?.some(row=>row.id===unrelated.data)).toBe(false);expect(visible?.every(row=>row.status==="SUBMITTED")).toBe(true)});
  it("allows progression after full completion and records normal evidence",async()=>{expect((await hr.rpc("feedback_completion",{p_candidate_id:gated,p_stage_id:stageIds[0]})).data?.[0]).toMatchObject({required_count:2,submitted_count:2,complete:true});expect((await hr.rpc("move_candidate",{p_candidate_id:gated,p_target_stage_id:stageIds[1]})).error).toBeNull();expect((await service.from("candidate_stage_history").select("id").eq("candidate_id",gated).eq("new_stage_id",stageIds[1])).data).toHaveLength(1);expect((await service.from("audit_events").select("id").eq("candidate_id",gated).eq("action","CANDIDATE_PROGRESSED")).data).toHaveLength(1)});
  it("ignores cancelled required assignments",async()=>{expect((await hr.rpc("feedback_completion",{p_candidate_id:cancelled,p_stage_id:stageIds[0]})).data?.[0]).toMatchObject({required_count:0,submitted_count:0,complete:true});expect((await hr.rpc("move_candidate",{p_candidate_id:cancelled,p_target_stage_id:stageIds[1]})).error).toBeNull()});
  it("records an accountable override atomically",async()=>{const reason="Required interviewer became unavailable; HR approved progression using the available evidence.";expect((await hr.rpc("move_candidate",{p_candidate_id:overrideCandidate,p_target_stage_id:stageIds[1],p_override:true,p_override_reason:reason})).error).toBeNull();const[{data:record},{data:history},{data:activity},{data:audit}]=await Promise.all([service.from("progression_overrides").select("from_stage_id,to_stage_id,actor_profile_id,reason,created_at").eq("candidate_id",overrideCandidate).single(),service.from("candidate_stage_history").select("previous_stage_id,new_stage_id,changed_by,changed_at").eq("candidate_id",overrideCandidate).single(),service.from("activity_logs").select("actor_id,metadata,created_at").eq("candidate_id",overrideCandidate).eq("action","PROGRESSION_OVERRIDDEN").single(),service.from("audit_events").select("actor_profile_id,metadata,created_at").eq("candidate_id",overrideCandidate).eq("action","PROGRESSION_OVERRIDDEN").single()]);expect(record).toMatchObject({from_stage_id:stageIds[0],to_stage_id:stageIds[1],actor_profile_id:hrId,reason});expect(history).toMatchObject({previous_stage_id:stageIds[0],new_stage_id:stageIds[1],changed_by:hrId});expect(activity?.metadata.reason).toBe(reason);expect(audit?.metadata.reason).toBe(reason);expect(record?.created_at&&history?.changed_at&&activity?.created_at&&audit?.created_at).toBeTruthy()});
  it("keeps submitted evidence visible to HR and Management but read-only",async()=>{for(const client of [hr,management]){const{data}=await client.from("feedback_submissions").select("id,status").eq("candidate_id",gated);expect(data?.length).toBeGreaterThanOrEqual(3);expect(data?.every(row=>row.status==="SUBMITTED")).toBe(true)}expect((await management.rpc("move_candidate",{p_candidate_id:gated,p_target_stage_id:stageIds[2]})).error).toBeTruthy();const{data:before}=await service.from("feedback_submissions").select("remarks").eq("id",feedbackIds[0]).single();await management.from("feedback_submissions").update({remarks:"Tampered"}).eq("id",feedbackIds[0]);const{data:after}=await service.from("feedback_submissions").select("remarks").eq("id",feedbackIds[0]).single();expect(after).toEqual(before)});
  it("preserves sequential-stage and closed-candidate protections",async()=>{expect((await hr.rpc("move_candidate",{p_candidate_id:noEvidence,p_target_stage_id:stageIds[0]})).error?.message).toContain("Only the next configured stage");expect((await hr.rpc("move_candidate",{p_candidate_id:closed,p_target_stage_id:stageIds[1]})).error?.message).toContain("Closed candidates cannot change stage")});
});
