import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";import{resolve}from"node:path";import{interviewSchema,interviewerAssignmentSchema}from"@/lib/validation";
const sql=readFileSync(resolve("supabase/migrations/202609120001_interview_management.sql"),"utf8");
const valid={candidate_id:"11111111-1111-4111-8111-111111111111",stage_id:"22222222-2222-4222-8222-222222222222",scheduled_at:new Date(Date.now()+86_400_000).toISOString(),timezone:"Asia/Colombo",method:"VIDEO",location:"",meeting_link:"https://meet.example.com/hirelens",notes:"Interview notes"};
describe("Phase B interview management contract",()=>{
  it("validates scheduling fields and method-specific details",()=>{expect(interviewSchema.safeParse(valid).success).toBe(true);expect(interviewSchema.safeParse({...valid,scheduled_at:new Date(0).toISOString()}).success).toBe(false);expect(interviewSchema.safeParse({...valid,method:"IN_PERSON",location:""}).success).toBe(false);expect(interviewSchema.safeParse({...valid,meeting_link:"http://unsafe.test"}).success).toBe(false)});
  it("validates unique interviewer selections",()=>{const interview_id="33333333-3333-4333-8333-333333333333",id="44444444-4444-4444-8444-444444444444";expect(interviewerAssignmentSchema.safeParse({interview_id,interviewer_ids:[id]}).success).toBe(true);expect(interviewerAssignmentSchema.safeParse({interview_id,interviewer_ids:[id,id]}).success).toBe(false)});
  it("derives vacancy context and stage validity inside the scheduling RPC",()=>{expect(sql).toContain("select * into c from public.candidates");expect(sql).toContain("id = p_stage_id and vacancy_id = c.vacancy_id");expect(sql).toContain("Candidate not found")});
  it("uses HR-only atomic scheduling, update and cancellation RPCs",()=>{for(const fn of ["schedule_interview","update_interview","cancel_interview"])expect(sql).toContain(`create function public.${fn}`);expect(sql.match(/if not public\.is_hr\(\)/g)?.length).toBeGreaterThanOrEqual(5);expect(sql).toContain("INTERVIEW_CREATED");expect(sql).toContain("INTERVIEW_UPDATED");expect(sql).toContain("INTERVIEW_CANCELLED")});
  it("keeps rescheduling on the same interview record",()=>{expect(sql).toContain("update public.interviews set stage_id=p_stage_id");expect(sql).not.toContain("RESCHEDULED")});
  it("restricts assignment to interviewer profiles and rejects duplicates",()=>{expect(sql).toContain("role='INTERVIEWER'");expect(sql).toContain("Duplicate interviewer selection is not permitted");expect(sql).toContain("Only INTERVIEWER profiles may be assigned")});
  it("creates assignment, feedback-required and schedule-change notifications",()=>{for(const value of ["INTERVIEW_ASSIGNED","FEEDBACK_REQUIRED","INTERVIEW_CHANGED"])expect(sql).toContain(value);expect(sql).toContain("public.create_notification")});
  it("limits helper execution and removes direct mutation bypasses",()=>{expect(sql).toContain("security definer set search_path = ''");expect(sql).toContain("revoke all on function public.list_assignable_interviewers() from public,anon");expect(sql).toContain("revoke insert,update,delete on public.interviews from authenticated");expect(sql).toContain("revoke insert,update,delete on public.interview_assignments from authenticated")});
});
