import{describe,expect,it}from"vitest";import{readFileSync}from"node:fs";import{average,csv,csvCell,deriveStageStays,normalized,selected,stageDurationDays}from"@/lib/reporting";import{summarizeSubmittedFeedback}from"@/lib/ai-feedback";
const root=process.cwd(),read=(path:string)=>readFileSync(`${root}/${path}`,"utf8"),candidates=read("app/(protected)/candidates/page.tsx"),vacancies=read("app/(protected)/vacancies/page.tsx"),dashboard=read("app/(protected)/dashboard/page.tsx"),analytics=read("app/(protected)/analytics/bottlenecks/page.tsx"),audit=read("app/(protected)/audit/page.tsx"),report=read("app/api/reports/recruitment.csv/route.ts"),decision=read("app/(protected)/candidates/[id]/decision-room/page.tsx"),layout=read("app/(protected)/layout.tsx"),migration=read("supabase/migrations/202609130001_reporting_analytics.sql");
describe("Phase F reporting helpers",()=>{
  it("calculates completed stage duration",()=>expect(stageDurationDays("2026-09-01T00:00:00Z","2026-09-03T12:00:00Z")).toBe(2.5));
  it("calculates current wait from the supplied clock",()=>expect(stageDurationDays("2026-09-01T00:00:00Z",null,new Date("2026-09-04T00:00:00Z"))).toBe(3));
  it("rejects malformed and negative durations",()=>{expect(stageDurationDays("bad",null)).toBeNull();expect(stageDurationDays("2026-09-03","2026-09-01")).toBeNull()});
  it("does not fabricate an empty average",()=>expect(average([null,null])).toBeNull());
  it("derives initial, completed, and active stays",()=>{const stays=deriveStageStays({id:"c",current_stage_id:"b",created_at:"2026-09-01T00:00:00Z",status:"ACTIVE"},[{candidate_id:"c",previous_stage_id:"a",new_stage_id:"b",changed_at:"2026-09-02T00:00:00Z"}],new Map([["a","Applied"],["b","Screening"]]));expect(stays).toEqual([{stageId:"a",stageName:"Applied",enteredAt:"2026-09-01T00:00:00Z",leftAt:"2026-09-02T00:00:00Z"},{stageId:"b",stageName:"Screening",enteredAt:"2026-09-02T00:00:00Z",leftAt:null}])});
  it("escapes commas, quotes, line breaks and emits UTF-8 BOM",()=>{expect(csvCell('Fernando, "Maya"')).toBe('"Fernando, ""Maya"""');expect(csv([["Name"],["Maya\nFernando"]])).toBe('\uFEFFName\r\n"Maya\nFernando"\r\n')});
  it("normalizes and allow-lists query values",()=>{expect(normalized(" Maya ")).toBe("Maya");expect(selected("DROP",["ACTIVE"])).toBe("")});
});
describe("Phase F feature contracts",()=>{
  it("provides candidate search and required filters",()=>{for(const value of["full_name.ilike","email.ilike","vacancy_id","current_stage_id","outcome","feedback_completion","Clear filters"])expect(candidates).toContain(value)});
  it("provides vacancy search, department, state, and sorting",()=>{for(const value of["ilike(\"title\"","department","ARCHIVED","Vacancy title","Clear filters"])expect(vacancies).toContain(value)});
  it("allows Management candidate access but keeps creation HR-only",()=>{expect(candidates).toContain('requireProfile(["HR_RECRUITER","MANAGEMENT"])');expect(candidates).toContain('profile.role==="HR_RECRUITER"&&<Link')});
  it("uses only stored management metrics",()=>{for(const value of["Active Vacancies","Active Candidates","Scheduled Interviews","Pending Required Feedback","Hired","Rejected","On Hold"])expect(dashboard).toContain(value);expect(dashboard).not.toMatch(/conversion|diversity|quality.of.hire|success probability/i)});
  it("documents analytics formulas and missing history",()=>{expect(analytics).toContain("stage entry to the next transition");expect(analytics).toContain("Not enough history");expect(analytics).toContain("Malformed or negative date ranges are excluded")});
  it("protects audit and export routes by role",()=>{expect(audit).toContain('requireProfile(["HR_RECRUITER","MANAGEMENT"])');expect(report).toContain('requireProfile(["HR_RECRUITER","MANAGEMENT"])')});
  it("keeps audit immutable and RPCs narrowly granted",()=>{expect(read("supabase/migrations/202609110001_sprint2_foundation.sql")).toContain("revoke insert, update, delete on public.audit_events from authenticated");expect(migration).toContain("Audit access is restricted");expect(migration).toContain("from public, anon");expect(migration).toContain("to authenticated")});
  it("exports only approved headers with private no-store delivery",()=>{for(const value of["Candidate Name","Vacancy","Current Stage","Outcome","Feedback Completion","Scheduled Interview Status","Current Stage Duration (Days)","private, no-store"])expect(report).toContain(value);expect(report).not.toMatch(/password|authentication_user_id|service.role/i)});
  it("records report exports through a role-checked RPC",()=>{expect(report).toContain("record_recruitment_report_export");expect(migration).toContain("RECRUITMENT_REPORT_EXPORTED")});
  it("keeps oversight navigation away from Interviewer",()=>{expect(layout).toContain('const oversight=profile.role==="HR_RECRUITER"||profile.role==="MANAGEMENT"');for(const link of["Bottlenecks","Audit","Reports"])expect(layout).toContain(link)});
  it("shows an honest unavailable AI boundary and source evidence",async()=>{const state=await summarizeSubmittedFeedback([]);expect(state.status).toBe("UNAVAILABLE");expect(decision).toContain("Final hiring decisions remain with authorised staff");expect(decision).toContain("View source feedback")});
  it("does not fake recommendations or hiring actions",()=>{expect(read("lib/ai-feedback.ts")).not.toMatch(/recommended hire|recommended reject|success probability|candidate ranking/i);expect(read("lib/ai-feedback.ts")).not.toContain("fetch(")});
});
