import Link from "next/link";
import { notFound } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { agreementSummary, criterionAverages, DISAGREEMENT_THRESHOLD, humanEvaluationAverage, type SubmittedEvaluation } from "@/lib/decision-support";
import { formatInterviewDate } from "@/lib/interviews";
import type { Candidate } from "@/lib/types";
import { summarizeSubmittedFeedback } from "@/lib/ai-feedback";

type Evidence={id:string;stage_name:string;interview_id:string|null;author_name:string;remarks:string;submitted_at:string};
type Override={id:string;reason:string;created_at:string;from_stage:{name:string}|null;to_stage:{name:string}|null;actor:{full_name:string}|null};

export default async function DecisionRoom({params}:{params:Promise<{id:string}>}){
  await requireProfile(["HR_RECRUITER","MANAGEMENT"]);
  const{id}=await params;const s=await createClient();
  const{data:candidate}=await s.from("candidates").select("*,vacancy:vacancies(id,title),current_stage:vacancy_stages(id,name)").eq("id",id).single();
  if(!candidate)notFound();const c=candidate as Candidate;
  const[{data:completion},{data:disagreement},{data:evaluations},{data:evidence},{data:overrides}]=await Promise.all([
    s.rpc("feedback_completion",{p_candidate_id:id,p_stage_id:c.current_stage_id}),
    s.rpc("feedback_disagreement",{p_candidate_id:id,p_stage_id:c.current_stage_id}),
    s.from("feedback_submissions").select("id,candidate_id,stage_id,interview_id,remarks,strengths,concerns,submitted_at,author:user_profiles!feedback_submissions_author_profile_id_fkey(full_name),feedback_ratings(criterion_id,criterion_name,criterion_weight,rating)").eq("candidate_id",id).eq("stage_id",c.current_stage_id).eq("status","SUBMITTED").eq("author_role","INTERVIEWER").not("interview_id","is",null).order("submitted_at"),
    s.rpc("candidate_feedback_evidence",{p_candidate_id:id}),
    s.from("progression_overrides").select("id,reason,created_at,from_stage:vacancy_stages!progression_overrides_from_stage_id_fkey(name),to_stage:vacancy_stages!progression_overrides_to_stage_id_fkey(name),actor:user_profiles!progression_overrides_actor_profile_id_fkey(full_name)").eq("candidate_id",id).order("created_at",{ascending:false}),
  ]);
  const rows=(evaluations??[])as unknown as SubmittedEvaluation[];const agreement=agreementSummary(rows);const databaseDifference=disagreement===null?null:Number(disagreement);if(agreement.difference!==null&&databaseDifference!==agreement.difference)throw new Error("Agreement evidence is inconsistent.");const criteria=criterionAverages(rows);const average=humanEvaluationAverage(rows);const progress=completion?.[0] as {required_count:number;submitted_count:number;complete:boolean}|undefined;const readiness=c.status!=="ACTIVE"?"CLOSED":progress?.complete?"READY":"BLOCKED";const aiSummary=await summarizeSubmittedFeedback(rows);
  return <div className="stack decision-room"><div className="decision-hero"><div><Link className="muted" href={`/candidates/${id}`}>← Candidate details</Link><p className="eyebrow">Decision room</p><h1>{c.full_name}</h1><p>{c.vacancy?.title}</p></div><Link className="btn secondary" href={`/vacancies/${c.vacancy_id}/compare?candidate=${id}`}>Compare candidates</Link></div>
    <section className="decision-grid"><div className="decision-stat"><span>Current stage</span><strong>{c.current_stage?.name}</strong></div><div className="decision-stat"><span>Decision readiness</span><strong className={readiness==="BLOCKED"?"blocked-state":""}>{readiness}</strong></div><div className="decision-stat"><span>Feedback</span><strong>{progress?.submitted_count??0} / {progress?.required_count??0} Complete</strong></div></section>
    <section className="card"><div className="section-heading"><div><p className="eyebrow">Evaluation evidence</p><h2>Human ratings</h2></div>{average!==null&&<div className="overall-score"><strong>{average}</strong><small>/ 5 Overall Human Rating</small></div>}</div>{criteria.size?<div className="stack">{[...criteria].map(([criterionId,item])=><div className="score-row" key={criterionId}><strong>{item.name}</strong><span>{item.average} / 5</span></div>)}<p className="muted">Weighted evaluations use the configured criterion weights. Unweighted evaluations use a simple rating average. Missing evidence is not counted as zero.</p></div>:<div className="empty-state"><strong>No submitted evaluation evidence available.</strong></div>}</section>
    <section className={`card agreement-panel ${agreement.status==="REVIEW"?"review-required":""}`}><p className="eyebrow">Interviewer agreement</p>{agreement.status==="INSUFFICIENT"?<><h2>Not enough submitted evaluations</h2><p>Additional submitted feedback is required before interviewer agreement can be assessed.</p></>:<><h2>{agreement.status==="REVIEW"?"⚠ HUMAN REVIEW REQUIRED":"GENERAL AGREEMENT"}</h2><p>{agreement.status==="REVIEW"?"Interviewer evaluations differ materially. Review the individual evidence before making a decision.":"Submitted interviewer evaluations are within the transparent agreement threshold."}</p><div className="agreement-metrics"><span>Highest <strong>{agreement.highest} / 5</strong></span><span>Lowest <strong>{agreement.lowest} / 5</strong></span><span>Difference <strong>{agreement.difference}</strong></span><span>Threshold <strong>{DISAGREEMENT_THRESHOLD}</strong></span></div></>}</section>
    <section className="card ai-summary"><p className="eyebrow">Responsible AI summary</p><h2>AI feedback summary</h2><div className="empty-state"><strong>AI summary unavailable</strong><p className="muted">{aiSummary.message}</p></div><p className="ai-disclaimer">AI-generated summaries, when configured, use submitted interviewer evidence only. Final hiring decisions remain with authorised staff.</p><a className="text-link" href="#source-feedback">View source feedback</a></section>
    <section className="card" id="source-feedback"><p className="eyebrow">Individual evidence</p><h2>Submitted interviewer feedback</h2>{rows.length?<div className="stack">{rows.map(row=><article className="evidence-card" key={row.id}><div className="section-heading"><h3>{row.author?.full_name??"Interviewer"}</h3><span className="badge">SUBMITTED</span></div>{row.feedback_ratings.map(rating=><div className="score-row" key={rating.criterion_id}><strong>{rating.criterion_name}</strong><span>{rating.rating} / 5</span></div>)}<h4>Remarks</h4><p>{row.remarks}</p><p className="muted">{row.submitted_at?formatInterviewDate(row.submitted_at):""}</p></article>)}</div>:<p className="muted">No submitted evaluation evidence available.</p>}</section>
    <section className="card"><p className="eyebrow">Stage evidence</p><h2>Historical remarks and feedback</h2>{evidence?.length?<div className="stack">{(evidence as Evidence[]).map(item=><article className="evidence-card" key={item.id}><span className="badge">{item.stage_name}</span><p>{item.remarks}</p><p className="muted">— {item.author_name} · {formatInterviewDate(item.submitted_at)}</p></article>)}</div>:<p className="muted">No remarks recorded.</p>}</section>
    <section className="card"><p className="eyebrow">Governance history</p><h2>Progression overrides</h2>{overrides?.length?<div className="stack">{(overrides as unknown as Override[]).map(item=><article className="evidence-card" key={item.id}><span className="badge draft">Progression override</span><h3>{item.from_stage?.name} → {item.to_stage?.name}</h3><p>{item.reason}</p><p className="muted">— {item.actor?.full_name??"HR recruiter"} · {formatInterviewDate(item.created_at)}</p></article>)}</div>:<p className="muted">No progression overrides recorded.</p>}</section>
    <section className="human-decision-note"><strong>Decision support, not an automated decision.</strong><p>HireLens presents submitted human evidence. HR and Management remain responsible for the hiring decision.</p></section>
  </div>
}
