"use client";
import { useActionState, useState } from "react"; import type { Candidate, Vacancy } from "@/lib/types";
import { archiveVacancy, recordOutcome, saveCandidate, saveStages, saveVacancy, uploadCv, type ActionState } from "@/app/(protected)/actions";
const initial:ActionState={};
function Notice({state}:{state:ActionState}){return state.error?<p className="error" role="alert">{state.error}</p>:state.success?<p className="badge" role="status">{state.success}</p>:null}
export function VacancyForm({vacancy}:{vacancy?:Vacancy}){const[state,action,pending]=useActionState(saveVacancy,initial);return <form action={action} className="stack">{vacancy&&<input type="hidden" name="id" value={vacancy.id}/>}<div className="grid2"><Field label="Title" name="title" value={vacancy?.title}/><Field label="Department" name="department" value={vacancy?.department}/><Field label="Location" name="location" value={vacancy?.location}/><label className="field">Employment type<select name="employment_type" defaultValue={vacancy?.employment_type??"FULL_TIME"}>{["FULL_TIME","PART_TIME","CONTRACT","TEMPORARY","INTERNSHIP"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label></div><label className="field">Description<textarea name="description" required minLength={20} defaultValue={vacancy?.description}/></label><Notice state={state}/><button className="btn" disabled={pending}>{pending?"Saving…":vacancy?"Save changes":"Create vacancy"}</button></form>}
export function ArchiveVacancyForm({vacancyId}:{vacancyId:string}){return <form action={archiveVacancy}><input type="hidden" name="id" value={vacancyId}/><button className="btn danger" onClick={(event)=>{if(!confirm("Archive this vacancy? Recruitment history will be retained."))event.preventDefault()}}>Archive</button></form>}
function Field({label,name,value,type="text"}:{label:string;name:string;value?:string;type?:string}){return <label className="field">{label}<input name={name} type={type} required defaultValue={value}/></label>}
export function CandidateForm({vacancies,candidate}:{vacancies:Pick<Vacancy,"id"|"title">[];candidate?:Candidate}){const[state,action,pending]=useActionState(saveCandidate,initial);return <form action={action} className="stack">{candidate&&<input type="hidden" name="id" value={candidate.id}/>}<div className="grid2"><label className="field">Vacancy<select name="vacancy_id" defaultValue={candidate?.vacancy_id} disabled={!!candidate}>{vacancies.map(v=><option value={v.id} key={v.id}>{v.title}</option>)}</select>{candidate&&<input type="hidden" name="vacancy_id" value={candidate.vacancy_id}/>}</label><Field label="Full name" name="full_name" value={candidate?.full_name}/><Field label="Email" name="email" type="email" value={candidate?.email}/><Field label="Phone" name="phone" type="tel" value={candidate?.phone}/><Field label="Source" name="source" value={candidate?.source}/></div><label className="field">Notes<textarea name="notes" defaultValue={candidate?.notes}/></label><Notice state={state}/><button className="btn" disabled={pending}>{pending?"Saving…":candidate?"Save changes":"Create candidate"}</button></form>}
export function CandidateOutcomeForm({candidateId,outcome}:{candidateId:string;outcome:Candidate["outcome"]}){return <form action={recordOutcome} style={{display:"flex",gap:8}}><input type="hidden" name="candidate_id" value={candidateId}/><select name="outcome" aria-label="Candidate outcome" defaultValue={outcome??"ON_HOLD"}>{["ON_HOLD","HIRED","REJECTED"].map(value=><option key={value}>{value}</option>)}</select><button className="btn danger" onClick={(event)=>{if(!confirm("Record this candidate outcome? The activity will be retained."))event.preventDefault()}}>Confirm outcome</button></form>}
export function StagesForm({vacancyId,initialNames}:{vacancyId:string;initialNames:string[]}){const[names,setNames]=useState(initialNames);const[state,action,pending]=useActionState(saveStages,initial);return <form action={action} className="stack"><input type="hidden" name="vacancy_id" value={vacancyId}/><input type="hidden" name="stages" value={JSON.stringify(names)}/>{names.map((name,index)=><div key={index} style={{display:"flex",gap:8}}><input aria-label={`Stage ${index+1}`} value={name} onChange={e=>setNames(x=>x.map((n,i)=>i===index?e.target.value:n))} style={{flex:1,padding:10,border:"1px solid #c9d5cf",borderRadius:8}}/><button type="button" className="btn secondary" disabled={index===0} onClick={()=>setNames(x=>x.map((n,i)=>i===index-1?x[index]:i===index?x[index-1]:n))}>↑</button><button type="button" className="btn secondary" disabled={index===names.length-1} onClick={()=>setNames(x=>x.map((n,i)=>i===index+1?x[index]:i===index?x[index+1]:n))}>↓</button><button type="button" className="btn danger" onClick={()=>setNames(x=>x.filter((_,i)=>i!==index))}>Remove</button></div>)}<button type="button" className="btn secondary" onClick={()=>setNames(x=>[...x,""])}>Add stage</button><Notice state={state}/><button className="btn" disabled={pending}>Save stage order</button></form>}
export function CvForm({candidateId}:{candidateId:string}){const[state,action,pending]=useActionState(uploadCv,initial);return <form action={action} className="stack"><input type="hidden" name="candidate_id" value={candidateId}/><label className="field">CV file (PDF, DOC, or DOCX; maximum 5 MB)<input name="cv" type="file" accept=".pdf,.doc,.docx" required/></label><Notice state={state}/><button className="btn" disabled={pending}>{pending?"Uploading…":"Attach or replace CV"}</button></form>}
