"use client";
import{useActionState,useMemo,useState}from"react";import{assignInterviewers,cancelInterview,createInterview,editInterview}from"@/app/(protected)/interviews/actions";import type{ActionState}from"@/app/(protected)/actions";import type{Interview,InterviewMethod,Stage}from"@/lib/types";
const initial:ActionState={};
function Notice({state}:{state:ActionState}){return state.error?<p className="error" role="alert">{state.error}</p>:state.success?<p className="badge" role="status">{state.success}</p>:null}
const pad=(value:number)=>String(value).padStart(2,"0");
function localParts(iso?:string){const d=iso?new Date(iso):new Date(Date.now()+86_400_000);return{date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}}
export function InterviewForm({candidateId,stages,interview}:{candidateId:string;stages:Stage[];interview?:Interview}){const defaults=useMemo(()=>localParts(interview?.scheduled_at),[interview?.scheduled_at]);const[date,setDate]=useState(defaults.date);const[time,setTime]=useState(defaults.time);const[method,setMethod]=useState<InterviewMethod>(interview?.method??"VIDEO");const actionFn=interview?editInterview:createInterview;const[state,action,pending]=useActionState(actionFn,initial);const timestamp=date&&time?new Date(`${date}T${time}:00`).toISOString():"";const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";return <form action={action} className="stack">{interview&&<input type="hidden" name="interview_id" value={interview.id}/>}<input type="hidden" name="candidate_id" value={candidateId}/><input type="hidden" name="scheduled_at" value={timestamp}/><input type="hidden" name="timezone" value={timezone}/><div className="grid2"><label className="field">Recruitment stage<select name="stage_id" defaultValue={interview?.stage_id} required>{stages.map(stage=><option key={stage.id} value={stage.id}>{stage.name}</option>)}</select></label><label className="field">Interview method<select name="method" value={method} onChange={event=>setMethod(event.target.value as InterviewMethod)}>{["IN_PERSON","VIDEO","PHONE"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label className="field">Date<input name="date" type="date" required value={date} onChange={event=>setDate(event.target.value)}/></label><label className="field">Time<input name="time" type="time" required value={time} onChange={event=>setTime(event.target.value)}/></label>{method==="IN_PERSON"&&<label className="field">Location<input name="location" required defaultValue={interview?.location??""}/></label>}{method==="VIDEO"&&<label className="field">Meeting link<input name="meeting_link" type="url" required placeholder="https://…" defaultValue={interview?.meeting_link??""}/></label>}</div><label className="field">Optional notes<textarea name="notes" maxLength={5000} defaultValue={interview?.notes}/></label><Notice state={state}/><button className="btn" disabled={pending}>{pending?"Saving…":interview?"Save interview":"Schedule interview"}</button></form>}
export function AssignmentForm({interviewId,profiles,assignedIds}:{interviewId:string;profiles:{id:string;full_name:string}[];assignedIds:string[]}){const[state,action,pending]=useActionState(assignInterviewers,initial);const available=profiles.filter(profile=>!assignedIds.includes(profile.id));return <form action={action} className="stack"><input type="hidden" name="interview_id" value={interviewId}/>{available.length?<fieldset className="stack" style={{border:0,padding:0}}><legend style={{fontWeight:800,marginBottom:10}}>Available interviewers</legend>{available.map(profile=><label key={profile.id} className="check-row"><input type="checkbox" name="interviewer_ids" value={profile.id}/><span>{profile.full_name}</span></label>)}</fieldset>:<p className="muted">All authorised interviewers are already assigned.</p>}<Notice state={state}/>{available.length>0&&<button className="btn" disabled={pending}>{pending?"Assigning…":"Save assignments"}</button>}</form>}
export function CancelInterviewForm({interviewId}:{interviewId:string}){return <form action={cancelInterview}><input type="hidden" name="interview_id" value={interviewId}/><button className="btn danger" onClick={event=>{if(!confirm("Cancel this interview? It will remain in the candidate history."))event.preventDefault()}}>Cancel interview</button></form>}
