import { expect, test, type Page } from "@playwright/test";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const service=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
let vacancyId="",stageId="",reviewerUserId="",reviewerProfileId="";
const candidateIds:string[]=[],interviewIds:string[]=[],feedbackIds:string[]=[],criterionIds:string[]=[];
let mayaId="",danielId="",reviewer:SupabaseClient;

async function client(email:string,password:string){const value=createClient(url,anon,{auth:{persistSession:false}});const{error}=await value.auth.signInWithPassword({email,password});if(error)throw error;return value}
async function profileId(value:SupabaseClient){const{data:{user}}=await value.auth.getUser();const{data,error}=await service.from("user_profiles").select("id").eq("authentication_user_id",user!.id).single();if(error)throw error;return data.id as string}
async function signIn(page:Page,email:string,password:string){await page.goto("/login");await page.getByLabel("Work email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20_000})}
async function signOut(page:Page){await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/\/login$/)}

test.describe("Phase E decision support journey",()=>{
  test.setTimeout(120_000);
  test.beforeAll(async()=>{
    const suffix=crypto.randomUUID();
    const[hr,interviewer]=await Promise.all([client(process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!),client("interviewer@hirelens.demo",process.env.SEED_INTERVIEWER_PASSWORD!)]);
    const[hrId,interviewerId]=await Promise.all([profileId(hr),profileId(interviewer)]);
    const reviewerEmail=`phase-e-browser-${suffix}@hirelens.test`,reviewerPassword=`PhaseE#${crypto.randomUUID()}aA1`;
    const{data:user,error:userError}=await service.auth.admin.createUser({email:reviewerEmail,password:reviewerPassword,email_confirm:true});if(userError)throw userError;reviewerUserId=user.user.id;
    const{data:profile,error:profileError}=await service.from("user_profiles").insert({authentication_user_id:reviewerUserId,full_name:"Phase E Browser Reviewer",role:"INTERVIEWER"}).select("id").single();if(profileError)throw profileError;reviewerProfileId=profile.id;reviewer=await client(reviewerEmail,reviewerPassword);
    const{data:vacancy,error:vacancyError}=await service.from("vacancies").insert({title:`Phase E Browser Decision Room ${suffix}`,department:"Decision Support QA",location:"Colombo",employment_type:"FULL_TIME",description:"Disposable Phase E browser verification fixture.",created_by:hrId}).select("id").single();if(vacancyError)throw vacancyError;vacancyId=vacancy.id;
    const{data:stage,error:stageError}=await service.from("vacancy_stages").insert({vacancy_id:vacancyId,name:"Final Interview",stage_order:0}).select("id").single();if(stageError)throw stageError;stageId=stage.id;
    const criteriaResult=await hr.rpc("save_evaluation_criteria",{p_vacancy_id:vacancyId,p_stage_id:stageId,p_criteria:[{id:null,name:"Technical Skills",description:"Technical evidence",weight:null,rating_required:true,display_order:0},{id:null,name:"Communication",description:"Communication evidence",weight:null,rating_required:false,display_order:1}]});if(criteriaResult.error)throw criteriaResult.error;
    const{data:criteria,error:criteriaError}=await service.from("evaluation_criteria").select("id").eq("vacancy_id",vacancyId).eq("stage_id",stageId).order("display_order");if(criteriaError)throw criteriaError;criterionIds.push(...criteria.map(row=>row.id));
    const{data:candidates,error:candidateError}=await service.from("candidates").insert([{vacancy_id:vacancyId,current_stage_id:stageId,full_name:"Maya Fernando",email:`maya-${suffix}@example.com`,phone:"+94 77 111 0001",source:"Phase E QA",notes:"Disposable",created_by:hrId},{vacancy_id:vacancyId,current_stage_id:stageId,full_name:"Daniel Silva",email:`daniel-${suffix}@example.com`,phone:"+94 77 111 0002",source:"Phase E QA",notes:"Disposable",created_by:hrId}]).select("id,full_name");if(candidateError)throw candidateError;candidateIds.push(...candidates.map(row=>row.id));mayaId=candidates.find(row=>row.full_name==="Maya Fernando")!.id;danielId=candidates.find(row=>row.full_name==="Daniel Silva")!.id;
    const scheduled=new Date(Date.now()+172_800_000).toISOString();const{data:interviews,error:interviewError}=await service.from("interviews").insert(candidateIds.map(candidate_id=>({candidate_id,vacancy_id:vacancyId,stage_id:stageId,scheduled_at:scheduled,timezone:"Asia/Colombo",method:"VIDEO",status:"SCHEDULED",created_by:hrId}))).select("id,candidate_id");if(interviewError)throw interviewError;interviewIds.push(...interviews.map(row=>row.id));
    const{error:assignmentError}=await service.from("interview_assignments").insert(interviews.flatMap(interview=>[{interview_id:interview.id,interviewer_profile_id:interviewerId,assigned_by:hrId,feedback_required:true},{interview_id:interview.id,interviewer_profile_id:reviewerProfileId,assigned_by:hrId,feedback_required:true}]));if(assignmentError)throw assignmentError;
    const interviewFor=(candidateId:string)=>interviews.find(row=>row.candidate_id===candidateId)!.id;
    const rating=(technical:number,communication?:number)=>[{criterion_id:criterionIds[0],rating:technical},...(communication===undefined?[]:[{criterion_id:criterionIds[1],rating:communication}])];
    for(const[value,candidateId,technical,communication,remarks]of[[interviewer,mayaId,4,4,"Maya demonstrates strong, consistent evidence."],[reviewer,mayaId,3,3,"Maya evidence remains aligned across reviewers."],[interviewer,danielId,5,undefined,"Daniel shows exceptional technical evidence."],[reviewer,danielId,2,undefined,"Daniel technical evidence requires human discussion."]]as[SupabaseClient,string,number,number|undefined,string][]){const result=await value.rpc("submit_interview_feedback",{p_interview_id:interviewFor(candidateId),p_remarks:remarks,p_strengths:"Evidence recorded by a human interviewer.",p_concerns:"Review in context.",p_ratings:rating(technical,communication)});if(result.error)throw result.error;feedbackIds.push(result.data)}
  });

  test.afterAll(async()=>{if(feedbackIds.length)await service.from("feedback_ratings").delete().in("feedback_submission_id",feedbackIds);if(candidateIds.length){await service.from("feedback_submissions").delete().in("candidate_id",candidateIds);for(const table of["notifications","progression_overrides","audit_events","activity_logs","candidate_stage_history"])await service.from(table).delete().in("candidate_id",candidateIds)}if(interviewIds.length){await service.from("interview_assignments").delete().in("interview_id",interviewIds);await service.from("interviews").delete().in("id",interviewIds)}if(vacancyId){await service.from("evaluation_criteria").delete().eq("vacancy_id",vacancyId);await service.from("audit_events").delete().eq("vacancy_id",vacancyId)}if(candidateIds.length)await service.from("candidates").delete().in("id",candidateIds);if(stageId)await service.from("vacancy_stages").delete().eq("id",stageId);if(vacancyId)await service.from("vacancies").delete().eq("id",vacancyId);if(reviewerProfileId)await service.from("user_profiles").delete().eq("id",reviewerProfileId);if(reviewerUserId)await service.auth.admin.deleteUser(reviewerUserId);await reviewer?.auth.signOut()});

  test("presents transparent evidence to HR and Management while denying Interviewer access",async({page})=>{
    await signIn(page,process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!);
    await page.goto(`/candidates/${mayaId}/decision-room`);await expect(page.getByRole("heading",{name:"Maya Fernando"})).toBeVisible();await expect(page.getByRole("heading",{name:"GENERAL AGREEMENT"})).toBeVisible();await expect(page.getByText("2 / 2 Complete")).toBeVisible();await expect(page.getByRole("heading",{name:"Submitted interviewer feedback"}).locator("..").getByText("Maya demonstrates strong, consistent evidence.")).toBeVisible();await expect(page.getByText("Decision support, not an automated decision.")).toBeVisible();
    await page.goto(`/candidates/${danielId}/decision-room`);await expect(page.getByRole("heading",{name:"⚠ HUMAN REVIEW REQUIRED"})).toBeVisible();await expect(page.getByText("Difference").locator("..")).toContainText("3");await expect(page.getByText("Threshold").locator("..")).toContainText("1.5");
    await page.goto(`/vacancies/${vacancyId}/compare?candidate=${mayaId}&candidate=${danielId}`);await expect(page.getByRole("columnheader",{name:"Maya Fernando"})).toBeVisible();await expect(page.getByRole("columnheader",{name:"Daniel Silva"})).toBeVisible();await expect(page.getByRole("row",{name:/Communication/})).toContainText("Not assessed");await expect(page.getByText("HireLens does not rank candidates or recommend a hiring outcome.")).toBeVisible();await expect(page.getByText(/Winner|Top Candidate|Recommended Hire/i)).toHaveCount(0);
    await signOut(page);await signIn(page,"management@hirelens.demo",process.env.SEED_MANAGEMENT_PASSWORD!);await page.goto(`/candidates/${danielId}/decision-room`);await expect(page.getByRole("heading",{name:"⚠ HUMAN REVIEW REQUIRED"})).toBeVisible();await expect(page.getByRole("button",{name:/Progress|Override|Edit|Save|Configure/i})).toHaveCount(0);await page.goto(`/vacancies/${vacancyId}/compare?candidate=${mayaId}&candidate=${danielId}`);await expect(page.getByRole("columnheader",{name:"Maya Fernando"})).toBeVisible();await expect(page.getByRole("button",{name:/Edit|Archive|Progress|Override/i})).toHaveCount(0);
    await signOut(page);await signIn(page,"interviewer@hirelens.demo",process.env.SEED_INTERVIEWER_PASSWORD!);await page.goto(`/candidates/${mayaId}/decision-room`);await expect(page).toHaveURL(/\/access-denied$/);await page.goto(`/vacancies/${vacancyId}/compare?candidate=${mayaId}&candidate=${danielId}`);await expect(page).toHaveURL(/\/access-denied$/);
  });
});
