import { expect, test, type Page } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";

const service=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
let vacancyId="",candidateId="",overrideCandidateId="",interviewId="",overrideInterviewId="",otherUserId="",otherProfileId="";

async function signIn(page:Page,email:string,password:string){await page.goto("/login");await page.getByLabel("Work email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await expect(page).toHaveURL(/\/dashboard$/,{timeout:20_000})}
async function signOut(page:Page){await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/\/login$/)}
async function createCandidate(page:Page,name:string,email:string){await page.goto("/candidates/new");await page.getByLabel("Vacancy").selectOption(vacancyId);await page.getByLabel("Full name").fill(name);await page.getByLabel("Email").fill(email);await page.getByLabel("Phone").fill("+94 77 987 6543");await page.getByLabel("Source").fill("Phase D QA");await page.getByRole("button",{name:"Create candidate"}).click();await expect(page).toHaveURL(/\/candidates\/[a-f0-9-]+$/);return new URL(page.url()).pathname.split("/").pop()!}
async function schedule(page:Page,assignees:string[]){await page.getByRole("link",{name:"Schedule interview"}).click();await page.getByLabel("Recruitment stage").selectOption({label:"Applied"});const future=new Date(Date.now()+172_800_000);await page.getByLabel("Date").fill(`${future.getFullYear()}-${String(future.getMonth()+1).padStart(2,"0")}-${String(future.getDate()).padStart(2,"0")}`);await page.getByLabel("Time").fill("13:00");await page.getByLabel("Interview method").selectOption("VIDEO");await page.getByLabel("Meeting link").fill("https://meet.example.com/phase-d-governance");await page.getByRole("button",{name:"Schedule interview"}).click();await expect(page).toHaveURL(/\/interviews\/[a-f0-9-]+$/);const id=new URL(page.url()).pathname.split("/").pop()!;await page.getByRole("link",{name:"Assign interviewer"}).click();for(const name of assignees)await page.getByLabel(name).check();await page.getByRole("button",{name:"Save assignments"}).click();await expect(page.getByText("Interviewers assigned and notified.")).toBeVisible();return id}
async function submitFeedback(page:Page,candidateName:string,score:string,remarks:string){const card=page.getByRole("article").filter({hasText:candidateName});await card.getByRole("link",{name:/View interview|Complete feedback/}).click();await expect(page).toHaveURL(/\/interviews\/[a-f0-9-]+$/);await page.getByRole("link",{name:"Complete feedback"}).click();await expect(page.getByRole("heading",{name:"Your evaluation"})).toBeVisible();for(const option of await page.getByText(score,{exact:true}).all())await option.click();await page.getByLabel("Remarks").fill(remarks);await page.getByLabel("Strengths").fill("Relevant evidence recorded independently.");await page.getByLabel("Concerns").fill("No material concern.");await page.getByRole("button",{name:"Submit feedback"}).click();await expect(page.getByText("✓ Submitted")).toBeVisible();await page.getByRole("link",{name:"View submitted feedback"}).click();await expect(page.getByText("Submitted evidence is locked and cannot be edited.")).toBeVisible()}

test.describe("Phase D governance journey",()=>{
  test.setTimeout(180_000);
  let otherEmail="",otherPassword="";
  test.beforeAll(async()=>{const suffix=crypto.randomUUID();otherEmail=`phase-d-browser-${suffix}@hirelens.test`;otherPassword=`PhaseD#${crypto.randomUUID()}aA1`;const{data:user,error}=await service.auth.admin.createUser({email:otherEmail,password:otherPassword,email_confirm:true});if(error)throw error;otherUserId=user.user.id;const{data:profile,error:profileError}=await service.from("user_profiles").insert({authentication_user_id:otherUserId,full_name:"Phase D Browser Reviewer",role:"INTERVIEWER"}).select("id").single();if(profileError)throw profileError;otherProfileId=profile.id});
  test.afterAll(async()=>{const candidates=[candidateId,overrideCandidateId].filter(Boolean);if(candidates.length){const{data:feedback}=await service.from("feedback_submissions").select("id").in("candidate_id",candidates);const feedbackIds=(feedback??[]).map(row=>row.id);if(feedbackIds.length)await service.from("feedback_ratings").delete().in("feedback_submission_id",feedbackIds);await service.from("feedback_submissions").delete().in("candidate_id",candidates);for(const table of ["notifications","progression_overrides","audit_events","activity_logs","candidate_stage_history"])await service.from(table).delete().in("candidate_id",candidates)}const interviews=[interviewId,overrideInterviewId].filter(Boolean);if(interviews.length){await service.from("interview_assignments").delete().in("interview_id",interviews);await service.from("interviews").delete().in("id",interviews)}if(vacancyId){await service.from("evaluation_criteria").delete().eq("vacancy_id",vacancyId);await service.from("audit_events").delete().eq("vacancy_id",vacancyId)}if(candidates.length)await service.from("candidates").delete().in("id",candidates);if(vacancyId){await service.from("vacancy_stages").delete().eq("vacancy_id",vacancyId);await service.from("vacancies").delete().eq("id",vacancyId)}if(otherProfileId)await service.from("user_profiles").delete().eq("id",otherProfileId);if(otherUserId)await service.auth.admin.deleteUser(otherUserId)});

  test("blocks incomplete evidence, releases independent feedback, progresses when ready, and records override",async({page})=>{
    const suffix=Date.now();await signIn(page,process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!);await page.goto("/vacancies/new");await page.getByLabel("Title").fill(`Phase D QA ${suffix}`);await page.getByLabel("Department").fill("Governance QA");await page.getByLabel("Location").fill("Colombo");await page.getByLabel("Description").fill("Disposable evidence-gated progression browser fixture.");await page.getByRole("button",{name:"Create vacancy"}).click();await expect(page).toHaveURL(/\/vacancies\/[a-f0-9-]+$/);vacancyId=new URL(page.url()).pathname.split("/").pop()!;await page.getByRole("link",{name:"Configure criteria"}).click();await page.getByRole("button",{name:"Add criterion"}).click();await page.getByLabel("Name").fill("Evidence Quality");await page.getByLabel("Description").fill("Quality of evidence supplied by the interviewer.");await page.getByRole("button",{name:"Save criteria"}).click();await expect(page.getByText("Evaluation criteria saved.")).toBeVisible();
    candidateId=await createCandidate(page,"Phase D Ready Candidate",`ready-${suffix}@example.com`);interviewId=await schedule(page,["Ira Patel","Phase D Browser Reviewer"]);await signOut(page);
    await signIn(page,otherEmail,otherPassword);await submitFeedback(page,"Phase D Ready Candidate","Strong","Independent reviewer B evidence.");await signOut(page);
    await signIn(page,process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!);await page.goto(`/candidates/${candidateId}`);await expect(page.getByText("1 / 2 Complete")).toBeVisible();await expect(page.locator(".governance-card > .section-heading .badge")).toHaveText("BLOCKED");await expect(page.getByText("○ Ira Patel")).toBeVisible();await expect(page.getByText("Candidate cannot progress yet.")).toBeVisible();await signOut(page);
    await signIn(page,"interviewer@hirelens.demo",process.env.SEED_INTERVIEWER_PASSWORD!);const readyCard=page.getByRole("article").filter({hasText:"Phase D Ready Candidate"});await readyCard.getByRole("link",{name:"View interview"}).click();await page.getByRole("link",{name:"Complete feedback"}).click();await expect(page.getByText("Other interviewer feedback will become available only after you submit your own evaluation.")).toBeVisible();await expect(page.getByText("Independent reviewer B evidence.")).toHaveCount(0);for(const option of await page.getByText("Excellent",{exact:true}).all())await option.click();await page.getByLabel("Remarks").fill("Independent reviewer A evidence.");await page.getByRole("button",{name:"Submit feedback"}).click();await page.getByRole("link",{name:"View submitted feedback"}).click();await expect(page.getByRole("heading",{name:"Other submitted feedback"})).toBeVisible();await expect(page.getByText("Independent reviewer B evidence.")).toBeVisible();await expect(page.getByText("Submitted evidence is locked and cannot be edited.")).toBeVisible();await signOut(page);
    await signIn(page,process.env.E2E_HR_EMAIL!,process.env.E2E_HR_PASSWORD!);await page.goto(`/candidates/${candidateId}`);await expect(page.getByText("2 / 2 Complete")).toBeVisible();await expect(page.locator(".governance-card > .section-heading .badge")).toHaveText("READY");await page.getByRole("button",{name:"Progress to Screening"}).click();await expect(page.getByRole("heading",{name:"Current stage"}).locator("..").getByText("Screening",{exact:true})).toBeVisible();
    overrideCandidateId=await createCandidate(page,"Phase D Override Candidate",`override-${suffix}@example.com`);overrideInterviewId=await schedule(page,["Ira Patel"]);await page.goto(`/candidates/${overrideCandidateId}`);await expect(page.getByText("0 / 1 Complete")).toBeVisible();await page.getByRole("button",{name:"Override progression"}).click();await expect(page.getByRole("heading",{name:"Override required evidence"})).toBeVisible();await page.getByLabel("Reason for override").fill("Required interviewer became unavailable; HR approved progression using available evidence.");await page.getByLabel(/I confirm this exceptional progression/).check();await page.getByRole("button",{name:"Confirm override"}).click();await expect(page.getByRole("heading",{name:"Current stage"}).locator("..").getByText("Screening",{exact:true})).toBeVisible();await page.reload();await expect(page.getByText("Progression override",{exact:true})).toBeVisible();await expect(page.locator(".override-history article p").first()).toHaveText("Required interviewer became unavailable; HR approved progression using available evidence.");await expect(page.getByText("Progression overridden",{exact:true})).toBeVisible();
    await signOut(page);await signIn(page,"management@hirelens.demo",process.env.SEED_MANAGEMENT_PASSWORD!);await page.goto(`/candidates/${overrideCandidateId}`);await expect(page.getByText("Progression override",{exact:true})).toBeVisible();await expect(page.locator(".override-history article p").first()).toHaveText("Required interviewer became unavailable; HR approved progression using available evidence.");await expect(page.getByRole("button",{name:/Progress|Override|Confirm/})).toHaveCount(0);
  });
});
