"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation";
import { requireProfile } from "@/lib/auth"; import { createClient } from "@/lib/supabase/server";
import { candidateSchema, cvSchema, outcomeSchema, stageNamesSchema, vacancySchema } from "@/lib/validation";

export type ActionState={error?:string;success?:string};
const message=(error:unknown)=>error instanceof Error?error.message:"The operation could not be completed.";
export async function saveVacancy(_:ActionState,fd:FormData):Promise<ActionState>{ const actor=await requireProfile(["HR_RECRUITER"]); const parsed=vacancySchema.safeParse(Object.fromEntries(fd)); if(!parsed.success)return{error:parsed.error.issues[0].message}; const supabase=await createClient(); const id=String(fd.get("id")??""); if(id){const {error}=await supabase.from("vacancies").update(parsed.data).eq("id",id).eq("status","ACTIVE");if(error)return{error:error.message};revalidatePath(`/vacancies/${id}`);return{success:"Vacancy updated."}} const {data,error}=await supabase.from("vacancies").insert({...parsed.data,created_by:actor.id}).select("id").single();if(error)return{error:error.message}; const {error:stageError}=await supabase.from("vacancy_stages").insert([{vacancy_id:data.id,name:"Applied",stage_order:0},{vacancy_id:data.id,name:"Screening",stage_order:1},{vacancy_id:data.id,name:"Offer",stage_order:2}]);if(stageError)return{error:stageError.message};redirect(`/vacancies/${data.id}`); }
export async function archiveVacancy(fd:FormData){await requireProfile(["HR_RECRUITER"]);const id=String(fd.get("id"));const supabase=await createClient();const {error}=await supabase.from("vacancies").update({status:"ARCHIVED",archived_at:new Date().toISOString()}).eq("id",id).eq("status","ACTIVE");if(error)throw new Error(error.message);revalidatePath("/vacancies");redirect("/vacancies");}
export async function saveStages(_:ActionState,fd:FormData):Promise<ActionState>{await requireProfile(["HR_RECRUITER"]);const vacancyId=String(fd.get("vacancy_id"));let payload:unknown;try{payload=JSON.parse(String(fd.get("stages")))}catch{return{error:"Invalid stage data."}}const parsed=stageNamesSchema.safeParse(payload);if(!parsed.success)return{error:parsed.error.issues[0].message};const supabase=await createClient();const {data:existing,error:readError}=await supabase.from("vacancy_stages").select("id,name,stage_order,candidates!candidates_current_stage_id_fkey(id)").eq("vacancy_id",vacancyId);if(readError)return{error:readError.message};const retained=new Set(parsed.data.map(n=>n.toLowerCase()));const inUse=existing?.find(s=>!retained.has(s.name.toLowerCase())&&s.candidates.length>0);if(inUse)return{error:`${inUse.name} cannot be removed while candidates are in that stage.`};
  try{for(const [index,name] of parsed.data.entries()){const found=existing?.find(s=>s.name.toLowerCase()===name.toLowerCase());if(found){const {error}=await supabase.from("vacancy_stages").update({name,stage_order:index+1000}).eq("id",found.id);if(error)throw error}else{const {error}=await supabase.from("vacancy_stages").insert({vacancy_id:vacancyId,name,stage_order:index+1000});if(error)throw error}}const removed=existing?.filter(s=>!retained.has(s.name.toLowerCase())).map(s=>s.id)??[];if(removed.length){const {error}=await supabase.from("vacancy_stages").delete().in("id",removed);if(error)throw error}for(const [index,name] of parsed.data.entries()){const {error}=await supabase.from("vacancy_stages").update({stage_order:index}).eq("vacancy_id",vacancyId).ilike("name",name);if(error)throw error}}catch(error){return{error:message(error)}}revalidatePath(`/vacancies/${vacancyId}`);return{success:"Recruitment stages saved."};}
export async function saveCandidate(_:ActionState,fd:FormData):Promise<ActionState>{const actor=await requireProfile(["HR_RECRUITER"]);const parsed=candidateSchema.safeParse(Object.fromEntries(fd));if(!parsed.success)return{error:parsed.error.issues[0].message};const supabase=await createClient();const id=String(fd.get("id")??"");if(id){const {error}=await supabase.from("candidates").update({full_name:parsed.data.full_name,email:parsed.data.email,phone:parsed.data.phone,source:parsed.data.source,notes:parsed.data.notes}).eq("id",id);if(error)return{error:error.message};await supabase.from("activity_logs").insert({candidate_id:id,actor_id:actor.id,action:"CANDIDATE_UPDATED",description:"Candidate details updated"});revalidatePath(`/candidates/${id}`);return{success:"Candidate updated."}}const {data:stage,error:stageError}=await supabase.from("vacancy_stages").select("id").eq("vacancy_id",parsed.data.vacancy_id).order("stage_order").limit(1).single();if(stageError||!stage)return{error:"Configure at least one vacancy stage first."};const {data,error}=await supabase.from("candidates").insert({...parsed.data,current_stage_id:stage.id,created_by:actor.id}).select("id").single();if(error)return{error:error.message};await supabase.from("activity_logs").insert({candidate_id:data.id,actor_id:actor.id,action:"CANDIDATE_CREATED",description:"Candidate record created"});redirect(`/candidates/${data.id}`);}
export async function moveCandidate(fd:FormData){await requireProfile(["HR_RECRUITER"]);const supabase=await createClient();const id=String(fd.get("candidate_id"));const {error}=await supabase.rpc("move_candidate",{p_candidate_id:id,p_target_stage_id:String(fd.get("target_stage_id"))});if(error)throw new Error(error.message);revalidatePath(`/candidates/${id}`);revalidatePath("/pipeline");}
export async function recordOutcome(fd:FormData){await requireProfile(["HR_RECRUITER"]);const outcome=outcomeSchema.parse(fd.get("outcome"));const id=String(fd.get("candidate_id"));const supabase=await createClient();const {error}=await supabase.rpc("record_candidate_outcome",{p_candidate_id:id,p_outcome:outcome});if(error)throw new Error(error.message);revalidatePath(`/candidates/${id}`);}
export async function uploadCv(_:ActionState,fd:FormData):Promise<ActionState>{const actor=await requireProfile(["HR_RECRUITER"]);const file=fd.get("cv");if(!(file instanceof File))return{error:"Choose a CV file."};const parsed=cvSchema.safeParse({size:file.size,type:file.type});if(!parsed.success)return{error:parsed.error.issues[0].message};const candidateId=String(fd.get("candidate_id"));const ext=file.name.split(".").pop()?.toLowerCase()??"bin";const path=`${candidateId}/cv-${crypto.randomUUID()}.${ext}`;const supabase=await createClient();const {data:old}=await supabase.from("candidate_documents").select("id,storage_path").eq("candidate_id",candidateId).maybeSingle();const {error:uploadError}=await supabase.storage.from("candidate-cvs").upload(path,file,{contentType:file.type});if(uploadError)return{error:uploadError.message};const record={candidate_id:candidateId,file_name:file.name.replace(/[^a-zA-Z0-9._ -]/g,"_"),storage_path:path,file_type:file.type,uploaded_by:actor.id,uploaded_at:new Date().toISOString()};const {error}=old?await supabase.from("candidate_documents").update(record).eq("id",old.id):await supabase.from("candidate_documents").insert(record);if(error){await supabase.storage.from("candidate-cvs").remove([path]);return{error:error.message}}if(old)await supabase.storage.from("candidate-cvs").remove([old.storage_path]);await supabase.from("activity_logs").insert({candidate_id:candidateId,actor_id:actor.id,action:old?"CV_REPLACED":"CV_ATTACHED",description:old?"Candidate CV replaced":"Candidate CV attached"});revalidatePath(`/candidates/${candidateId}`);return{success:old?"CV replaced.":"CV attached."};}
