import Link from "next/link";
import { notFound } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { agreementSummary, criterionAverages, type SubmittedEvaluation } from "@/lib/decision-support";
import type { Candidate, EvaluationCriterion, Vacancy } from "@/lib/types";

type CandidateView=Candidate&{current_stage:{id:string;name:string}|null};

export default async function CompareCandidates({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{candidate?:string|string[]}>}){
  await requireProfile(["HR_RECRUITER","MANAGEMENT"]);const{id}=await params;const query=await searchParams;const requested=[...(Array.isArray(query.candidate)?query.candidate:query.candidate?[query.candidate]:[])];const s=await createClient();
  const[{data:vacancy},{data:candidates},{data:criteria}]=await Promise.all([s.from("vacancies").select("*").eq("id",id).single(),s.from("candidates").select("*,current_stage:vacancy_stages(id,name)").eq("vacancy_id",id).order("full_name"),s.from("evaluation_criteria").select("*").eq("vacancy_id",id).eq("active",true).order("display_order")]);if(!vacancy)notFound();const v=vacancy as Vacancy;const candidateRows=(candidates??[])as unknown as CandidateView[];const allowed=new Set(candidateRows.map(item=>item.id));const invalid=requested.some(candidateId=>!allowed.has(candidateId));const selectedIds=[...new Set(requested.filter(candidateId=>allowed.has(candidateId)))].slice(0,4);const selected=candidateRows.filter(item=>selectedIds.includes(item.id));
  let evaluations:SubmittedEvaluation[]=[];if(selectedIds.length){const{data}=await s.from("feedback_submissions").select("id,candidate_id,stage_id,interview_id,remarks,strengths,concerns,submitted_at,feedback_ratings(criterion_id,criterion_name,criterion_weight,rating)").in("candidate_id",selectedIds).eq("status","SUBMITTED").eq("author_role","INTERVIEWER").not("interview_id","is",null);evaluations=(data??[])as unknown as SubmittedEvaluation[]}
  const states=new Map(await Promise.all(selected.map(async candidate=>{const[{data:completion},{data:overrides}]=await Promise.all([s.rpc("feedback_completion",{p_candidate_id:candidate.id,p_stage_id:candidate.current_stage_id}),s.from("progression_overrides").select("id").eq("candidate_id",candidate.id)]);const current=evaluations.filter(item=>item.candidate_id===candidate.id&&item.stage_id===candidate.current_stage_id);return[candidate.id,{completion:completion?.[0] as {required_count:number;submitted_count:number;complete:boolean}|undefined,agreement:agreementSummary(current),averages:criterionAverages(evaluations.filter(item=>item.candidate_id===candidate.id)),overrides:overrides?.length??0}]as const})));
  const configured=(criteria??[])as EvaluationCriterion[];const evidenceCriteria=new Map<string,string>();for(const criterion of configured)evidenceCriteria.set(criterion.id,criterion.name);for(const evaluation of evaluations)for(const rating of evaluation.feedback_ratings)evidenceCriteria.set(rating.criterion_id,rating.criterion_name);
  return <div className="stack comparison-page"><div className="decision-hero"><div><Link className="muted" href={`/vacancies/${id}`}>← Vacancy details</Link><p className="eyebrow">Candidate comparison</p><h1>{v.title}</h1><p>Compare submitted human evidence using consistent criterion identities.</p></div></div>
    <section className="card"><h2>Select candidates</h2><p className="muted">Choose two to four candidates from this vacancy. Display order is alphabetical and does not imply ranking.</p><form className="comparison-selector" method="get">{candidateRows.map(candidate=><label className="check-row" key={candidate.id}><input type="checkbox" name="candidate" value={candidate.id} defaultChecked={selectedIds.includes(candidate.id)}/><span><strong>{candidate.full_name}</strong><small>{candidate.current_stage?.name??"No stage"}</small></span></label>)}<button className="btn">Compare selected</button></form>{invalid&&<p className="error" role="alert">Candidates must belong to the same vacancy.</p>}</section>
    {!invalid&&selected.length<2&&<section className="empty-state"><strong>Select at least two candidates to compare.</strong><p className="muted">Missing evidence will be shown as Not assessed, never as zero.</p></section>}
    {!invalid&&selected.length>=2&&<section className="card comparison-wrap"><table className="comparison-table"><thead><tr><th>Evidence</th>{selected.map(candidate=><th key={candidate.id}><Link href={`/candidates/${candidate.id}/decision-room`}>{candidate.full_name}</Link></th>)}</tr></thead><tbody><tr><th>Current stage</th>{selected.map(candidate=><td key={candidate.id}>{candidate.current_stage?.name??"Not assessed"}</td>)}</tr><tr><th>Status</th>{selected.map(candidate=><td key={candidate.id}>{candidate.outcome??candidate.status}</td>)}</tr><tr><th>Feedback completion</th>{selected.map(candidate=>{const state=states.get(candidate.id)?.completion;return<td key={candidate.id}>{state?`${state.submitted_count} / ${state.required_count} Complete`:"Not assessed"}</td>})}</tr><tr><th>Decision readiness</th>{selected.map(candidate=>{const state=states.get(candidate.id)?.completion;return<td key={candidate.id}><span className={`badge ${state&&!state.complete?"closed":""}`}>{candidate.status!=="ACTIVE"?"CLOSED":state?.complete?"READY":"BLOCKED"}</span></td>})}</tr>{[...evidenceCriteria].map(([criterionId,name])=><tr key={criterionId}><th>{name}</th>{selected.map(candidate=>{const score=states.get(candidate.id)?.averages.get(criterionId)?.average;return<td key={candidate.id}>{score===undefined?<span className="muted">Not assessed</span>:`${score} / 5`}</td>})}</tr>)}<tr><th>Interviewer agreement</th>{selected.map(candidate=>{const agreement=states.get(candidate.id)?.agreement;return<td key={candidate.id}>{agreement?.status==="REVIEW"?<span className="badge closed">HUMAN REVIEW REQUIRED</span>:agreement?.status==="AGREEMENT"?<span className="badge">GENERAL AGREEMENT</span>:<span className="muted">Not enough submitted evaluations</span>}</td>})}</tr><tr><th>Governance history</th>{selected.map(candidate=><td key={candidate.id}>{states.get(candidate.id)?.overrides?`${states.get(candidate.id)?.overrides} override record(s)`:"No progression overrides"}</td>)}</tr><tr><th>Detailed evidence</th>{selected.map(candidate=><td key={candidate.id}><Link className="text-link" href={`/candidates/${candidate.id}/decision-room`}>Open Decision Room</Link></td>)}</tr></tbody></table></section>}
    <section className="human-decision-note"><strong>Evidence comparison only.</strong><p>HireLens does not rank candidates or recommend a hiring outcome. Humans make the decision.</p></section>
  </div>
}
